var array = [118, 116, 67, 128, 117, 146, 19, 40, 45, 37, 140, 105, 115, 133, 124, 47, 30, 7, 17, 88, 13, 33, 86, 119, 63, 35, 109, 144, 120, 81, 137, 111, 1, 113, 110, 2, 123, 56, 89, 73, 142, 125, 141, 46, 96, 16, 3, 150, 104, 100];
var barrElement00 = document.getElementById('element00');
var barrElement01 = document.getElementById('element01');
var barrElement02 = document.getElementById('element02');
var barrElement03 = document.getElementById('element03');
var barrElement04 = document.getElementById('element04');
var barrElement05 = document.getElementById('element05');
var barrElement06 = document.getElementById('element06');
var barrElement07 = document.getElementById('element07');
var barrElement08 = document.getElementById('element08');
var barrElement09 = document.getElementById('element09');
var barrElement10 = document.getElementById('element10');
var barrElement11 = document.getElementById('element11');
var barrElement12 = document.getElementById('element12');
var barrElement13 = document.getElementById('element13');
var barrElement14 = document.getElementById('element14');
var barrElement15 = document.getElementById('element15');
var barrElement16 = document.getElementById('element16');
var barrElement17 = document.getElementById('element17');
var barrElement18 = document.getElementById('element18');
var barrElement19 = document.getElementById('element19');
var barrElement20 = document.getElementById('element20');
var barrElement21 = document.getElementById('element21');
var barrElement22 = document.getElementById('element22');
var barrElement23 = document.getElementById('element23');
var barrElement24 = document.getElementById('element24');
var barrElement25 = document.getElementById('element25');
var barrElement26 = document.getElementById('element26');
var barrElement27 = document.getElementById('element27');
var barrElement28 = document.getElementById('element28');
var barrElement29 = document.getElementById('element29');
var barrElement30 = document.getElementById('element30');
var barrElement31 = document.getElementById('element31');
var barrElement32 = document.getElementById('element32');
var barrElement33 = document.getElementById('element33');
var barrElement34 = document.getElementById('element34');
var barrElement35 = document.getElementById('element35');
var barrElement36 = document.getElementById('element36');
var barrElement37 = document.getElementById('element37');
var barrElement38 = document.getElementById('element38');
var barrElement39 = document.getElementById('element39');
var barrElement40 = document.getElementById('element40');
var barrElement41 = document.getElementById('element41');
var barrElement42 = document.getElementById('element42');
var barrElement43 = document.getElementById('element43');
var barrElement44 = document.getElementById('element44');
var barrElement45 = document.getElementById('element45');
var barrElement46 = document.getElementById('element46');
var barrElement47 = document.getElementById('element47');
var barrElement48 = document.getElementById('element48');
var barrElement49 = document.getElementById('element49');
var barrElement50 = document.getElementById('element50');
barrElement00.style.height = array[0]*5 + "px";
barrElement01.style.height = array[1]*5 + "px";
barrElement02.style.height = array[2]*5 + "px";
barrElement03.style.height = array[3]*5 + "px";
barrElement04.style.height = array[4]*5 + "px";
barrElement05.style.height = array[5]*5 + "px";
barrElement06.style.height = array[6]*5 + "px";
barrElement07.style.height = array[7]*5 + "px";
barrElement08.style.height = array[8]*5 + "px";
barrElement09.style.height = array[9]*5 + "px";
barrElement10.style.height = array[10]*5 + "px";
barrElement11.style.height = array[11]*5 + "px";
barrElement12.style.height = array[12]*5 + "px";
barrElement13.style.height = array[13]*5 + "px";
barrElement14.style.height = array[14]*5 + "px";
barrElement15.style.height = array[15]*5 + "px";
barrElement16.style.height = array[16]*5 + "px";
barrElement17.style.height = array[17]*5 + "px";
barrElement18.style.height = array[18]*5 + "px";
barrElement19.style.height = array[19]*5 + "px";
barrElement20.style.height = array[20]*5 + "px";
barrElement21.style.height = array[21]*5 + "px";
barrElement22.style.height = array[22]*5 + "px";
barrElement23.style.height = array[23]*5 + "px";
barrElement24.style.height = array[24]*5 + "px";
barrElement25.style.height = array[25]*5 + "px";
barrElement26.style.height = array[26]*5 + "px";
barrElement27.style.height = array[27]*5 + "px";
barrElement28.style.height = array[28]*5 + "px";
barrElement29.style.height = array[29]*5 + "px";
barrElement30.style.height = array[30]*5 + "px";
barrElement31.style.height = array[31]*5 + "px";
barrElement32.style.height = array[32]*5 + "px";
barrElement33.style.height = array[33]*5 + "px";
barrElement34.style.height = array[34]*5 + "px";
barrElement35.style.height = array[35]*5 + "px";
barrElement36.style.height = array[36]*5 + "px";
barrElement37.style.height = array[37]*5 + "px";
barrElement38.style.height = array[38]*5 + "px";
barrElement39.style.height = array[39]*5 + "px";
barrElement40.style.height = array[40]*5 + "px";
barrElement41.style.height = array[41]*5 + "px";
barrElement42.style.height = array[42]*5 + "px";
barrElement43.style.height = array[43]*5 + "px";
barrElement44.style.height = array[44]*5 + "px";
barrElement45.style.height = array[45]*5 + "px";
barrElement46.style.height = array[46]*5 + "px";
barrElement47.style.height = array[47]*5 + "px";
barrElement48.style.height = array[48]*5 + "px";
barrElement49.style.height = array[49]*5 + "px";
console.log(array[0]);
console.log("Script module Nº2 is Ok");
bubblesort(array);
console.log(array[0]);
console.log("Script module Nº2 is Ok");
setTimeout(function() {
    barrElement00.style.height = array[0]*5 + "px";
barrElement01.style.height = array[1]*5 + "px";
barrElement02.style.height = array[2]*5 + "px";
barrElement03.style.height = array[3]*5 + "px";
barrElement04.style.height = array[4]*5 + "px";
barrElement05.style.height = array[5]*5 + "px";
barrElement06.style.height = array[6]*5 + "px";
barrElement07.style.height = array[7]*5 + "px";
barrElement08.style.height = array[8]*5 + "px";
barrElement09.style.height = array[9]*5 + "px";
barrElement10.style.height = array[10]*5 + "px";
barrElement11.style.height = array[11]*5 + "px";
barrElement12.style.height = array[12]*5 + "px";
barrElement13.style.height = array[13]*5 + "px";
barrElement14.style.height = array[14]*5 + "px";
barrElement15.style.height = array[15]*5 + "px";
barrElement16.style.height = array[16]*5 + "px";
barrElement17.style.height = array[17]*5 + "px";
barrElement18.style.height = array[18]*5 + "px";
barrElement19.style.height = array[19]*5 + "px";
barrElement20.style.height = array[20]*5 + "px";
barrElement21.style.height = array[21]*5 + "px";
barrElement22.style.height = array[22]*5 + "px";
barrElement23.style.height = array[23]*5 + "px";
barrElement24.style.height = array[24]*5 + "px";
barrElement25.style.height = array[25]*5 + "px";
barrElement26.style.height = array[26]*5 + "px";
barrElement27.style.height = array[27]*5 + "px";
barrElement28.style.height = array[28]*5 + "px";
barrElement29.style.height = array[29]*5 + "px";
barrElement30.style.height = array[30]*5 + "px";
barrElement31.style.height = array[31]*5 + "px";
barrElement32.style.height = array[32]*5 + "px";
barrElement33.style.height = array[33]*5 + "px";
barrElement34.style.height = array[34]*5 + "px";
barrElement35.style.height = array[35]*5 + "px";
barrElement36.style.height = array[36]*5 + "px";
barrElement37.style.height = array[37]*5 + "px";
barrElement38.style.height = array[38]*5 + "px";
barrElement39.style.height = array[39]*5 + "px";
barrElement40.style.height = array[40]*5 + "px";
barrElement41.style.height = array[41]*5 + "px";
barrElement42.style.height = array[42]*5 + "px";
barrElement43.style.height = array[43]*5 + "px";
barrElement44.style.height = array[44]*5 + "px";
barrElement45.style.height = array[45]*5 + "px";
barrElement46.style.height = array[46]*5 + "px";
barrElement47.style.height = array[47]*5 + "px";
barrElement48.style.height = array[48]*5 + "px";
barrElement49.style.height = array[49]*5 + "px";
}, 5000);


//convercion *50
/*var numeros = [];
for (var i = 0; i < 50; i++) {
    numeros.push(Math.floor(Math.random() * 151));
}

// Desordenar los números
numeros.sort(function(a, b){return 0.5 - Math.random()});

// Convertir el array a una cadena separada por comas
var numerosSeparadosPorComas = numeros.join(', ');

console.log(numerosSeparadosPorComas);*/